apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: repro
on:
  workflow_dispatch: {}
jobs:
  test:
    steps:
      - name: Compute version
        id: version
        uses: docker://alpine/git:2.43.0
        run: |
          set -euo pipefail
          echo "SHA=test" >> $CLOUDBEES_OUTPUTS
