apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: bug-repro-caller
on:
  workflow_dispatch:

jobs:
  select:
    if: false
    with:
      instructions: "should never run"
      approvalInputs: |
        foo:
          type: choice
          options:
            - bar
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1

  run:
    needs: select
    if: false
    uses: ./.cloudbees/workflows/bug-repro-callee.yaml
    with:
      value: ${{ fromJSON(needs.select.outputs.approvalInputValues || '{"foo":"fallback"}').foo }}
